---
apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
    app: alpine
spec:
  restartPolicy: Never
  containers:
    - name: sleep
      image: alpine:3
      command: ["sleep", "300"]
      
      securityContext:
        appArmorProfile:
          type: Localhost
          localhostProfile: test-recording-test-pod
