[package]
name = "demobinary"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
env_logger = "0.11" 
libc = "0.2"
log = "0.4"

[[bin]]
name = "demobinary"
path = "main.rs"
