/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package sourcefakes

import (
	"sync"

	"sigs.k8s.io/security-profiles-operator/internal/pkg/daemon/enricher/source"
	"sigs.k8s.io/security-profiles-operator/internal/pkg/daemon/enricher/types"
)

type FakeAuditLineSource struct {
	StartTailStub        func() (chan *types.AuditLine, error)
	startTailMutex       sync.RWMutex
	startTailArgsForCall []struct {
	}
	startTailReturns struct {
		result1 chan *types.AuditLine
		result2 error
	}
	startTailReturnsOnCall map[int]struct {
		result1 chan *types.AuditLine
		result2 error
	}
	TailErrStub        func() error
	tailErrMutex       sync.RWMutex
	tailErrArgsForCall []struct {
	}
	tailErrReturns struct {
		result1 error
	}
	tailErrReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuditLineSource) StartTail() (chan *types.AuditLine, error) {
	fake.startTailMutex.Lock()
	ret, specificReturn := fake.startTailReturnsOnCall[len(fake.startTailArgsForCall)]
	fake.startTailArgsForCall = append(fake.startTailArgsForCall, struct {
	}{})
	stub := fake.StartTailStub
	fakeReturns := fake.startTailReturns
	fake.recordInvocation("StartTail", []interface{}{})
	fake.startTailMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuditLineSource) StartTailCallCount() int {
	fake.startTailMutex.RLock()
	defer fake.startTailMutex.RUnlock()
	return len(fake.startTailArgsForCall)
}

func (fake *FakeAuditLineSource) StartTailCalls(stub func() (chan *types.AuditLine, error)) {
	fake.startTailMutex.Lock()
	defer fake.startTailMutex.Unlock()
	fake.StartTailStub = stub
}

func (fake *FakeAuditLineSource) StartTailReturns(result1 chan *types.AuditLine, result2 error) {
	fake.startTailMutex.Lock()
	defer fake.startTailMutex.Unlock()
	fake.StartTailStub = nil
	fake.startTailReturns = struct {
		result1 chan *types.AuditLine
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditLineSource) StartTailReturnsOnCall(i int, result1 chan *types.AuditLine, result2 error) {
	fake.startTailMutex.Lock()
	defer fake.startTailMutex.Unlock()
	fake.StartTailStub = nil
	if fake.startTailReturnsOnCall == nil {
		fake.startTailReturnsOnCall = make(map[int]struct {
			result1 chan *types.AuditLine
			result2 error
		})
	}
	fake.startTailReturnsOnCall[i] = struct {
		result1 chan *types.AuditLine
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditLineSource) TailErr() error {
	fake.tailErrMutex.Lock()
	ret, specificReturn := fake.tailErrReturnsOnCall[len(fake.tailErrArgsForCall)]
	fake.tailErrArgsForCall = append(fake.tailErrArgsForCall, struct {
	}{})
	stub := fake.TailErrStub
	fakeReturns := fake.tailErrReturns
	fake.recordInvocation("TailErr", []interface{}{})
	fake.tailErrMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuditLineSource) TailErrCallCount() int {
	fake.tailErrMutex.RLock()
	defer fake.tailErrMutex.RUnlock()
	return len(fake.tailErrArgsForCall)
}

func (fake *FakeAuditLineSource) TailErrCalls(stub func() error) {
	fake.tailErrMutex.Lock()
	defer fake.tailErrMutex.Unlock()
	fake.TailErrStub = stub
}

func (fake *FakeAuditLineSource) TailErrReturns(result1 error) {
	fake.tailErrMutex.Lock()
	defer fake.tailErrMutex.Unlock()
	fake.TailErrStub = nil
	fake.tailErrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuditLineSource) TailErrReturnsOnCall(i int, result1 error) {
	fake.tailErrMutex.Lock()
	defer fake.tailErrMutex.Unlock()
	fake.TailErrStub = nil
	if fake.tailErrReturnsOnCall == nil {
		fake.tailErrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.tailErrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuditLineSource) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.startTailMutex.RLock()
	defer fake.startTailMutex.RUnlock()
	fake.tailErrMutex.RLock()
	defer fake.tailErrMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuditLineSource) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ source.AuditLineSource = new(FakeAuditLineSource)
