apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: security-profiles-operator
  newName: ghcr.io/mhils/security-profiles-operator
  newTag: latest
  # For images to be released:
  # newName: registry.k8s.io/security-profiles-operator/security-profiles-operator
  # newTag: v0.8.5


resources:
- manager_deployment.yaml
labels:
- includeSelectors: true
  pairs:
    app: security-profiles-operator
