---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: runc-v1.2.3
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - arch_prctl
        - brk
        - exit_group
        - getuid
        - mmap
        - mprotect
        - nanosleep
        - set_tid_address
