---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: runc-v1.2.3
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - arch_prctl
        - brk
        - chdir
        - chroot
        - close
        - epoll_ctl
        - epoll_pwait
        - execve
        - exit_group
        - faccessat2
        - fchmodat
        - fchownat
        - fcntl
        - fstatfs
        - futex
        - getcwd
        - getdents64
        - getpid
        - getuid
        - madvise
        - mkdirat
        - mmap
        - mount
        - mprotect
        - nanosleep
        - newfstatat
        - openat
        - openat2
        - pivot_root
        - read
        - rt_sigprocmask
        - rt_sigreturn
        - sched_yield
        - set_tid_address
        - sigaltstack
        - symlinkat
        - unlinkat
        - utimensat
        - write
