---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  labels:
    app: alpine
spec:
  restartPolicy: Never
  containers:
    - name: foo
      image: alpine:3
      command: ["/bin/sh", "-c", "touch /tmp/foo && sleep 10"]
